[package]
name = "multithreading"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backoff = "0.4.0"
colored = "2.1.0"
crossbeam-channel = "0.5.10"
parking_lot = "0.12.1"
