[package]
name = "fundamentals"
version = "0.1.0"
edition = "2021"

[lib]

name = "activity"
path = "src/activity_lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime = "2.1.0"
chrono = "0.4.31"
thiserror = "1.0"
